apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: contosopos
spec:
  template:
    metadata:
      name: init-db
    spec:
      containers:
      - name: contosodb
        image: postgres:15.0
        env:
        - name: PGHOST
          value: contosodb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin123
        - name: PGPASSWORD
          value: admin123          
        - name: POSTGRES_DB
          value: contoso
        command:
          - sh
          - -c
          - |
            psql -h $PGHOST -U postgres -d contoso  -c "CREATE SCHEMA contoso;"
            psql -h $PGHOST -U postgres -d contoso  -c "CREATE TABLE contoso.products (productId SERIAL PRIMARY KEY, name text, description text, price numeric, stock int, photopath text, category text);"
            psql -h $PGHOST -U postgres -d contoso  -c "CREATE TABLE contoso.Orders ( orderID SERIAL PRIMARY KEY, orderDate timestamp, orderdetails JSON, storeId INT, cloudSynced int default 0);"
            psql -h $PGHOST -U postgres -d contoso  -c "INSERT INTO contoso.products (name, description, price, stock, photopath, category) VALUES ('Red Apple', 'Contoso Fresh Fuji Red Apples', 0.5, 10000, 'static/img/product1.jpg', 'Fruits'), ('Banana', 'Contoso Fresh Cavendish Bananas', 1, 10000, 'static/img/product2.jpg', 'Fruits'), ('Avocado', 'Contoso Fresh Hass Avocado', 1.5, 10000, 'static/img/product3.jpg', 'Vegetables'), ('Bread', 'Instore Bakery Fresh Bread Rolls 6 pack', .80, 10000, 'static/img/product4.jpg', 'Bread'), ('Milk', 'Contoso Full Milk', 0.95, 10000, 'static/img/product5.jpg', 'Dairy'), ('Orange Juice', 'Contoso Premium Juice', 4, 10000, 'static/img/product6.jpg', 'Beverages'), ('Chips', 'Contoso Crinkle Cut Chips', 2.0, 10000, 'static/img/product7.jpg', 'Snacks'), ('Red Pepper', 'Contoso Fresh Red Pepper', 3.5, 10000, 'static/img/product8.jpg', 'Vegetables'), ('Lettuce', 'Fresh Vegetable Cos Lettuce', 7, 10000, 'static/img/product9.jpg', 'Vegetables'), ('Tomato', 'Contoso Fresh Vine Tomatoes', 1, 10000, 'static/img/product10.jpg', 'Vegetables'), ('Strawberry', 'Contoso Fresh Allstar Strawberries', 1, 10000, 'static/img/product11.jpg', 'Fruit'), ('Eggs', 'Free Range Contoso Dozen Eggs', 1, 10000, 'static/img/product12.jpg', 'Eggs'), ('Lemon', 'Contoso Lisbon Lemons', 1, 10000, 'static/img/product13.jpg', 'Fruit');"
            psql -h $PGHOST -U postgres -d contoso  -c "Commit;"
        volumeMounts:
        - name: postgresql-vol
          mountPath: /var/lib/postgresql/data
      restartPolicy: Never
      volumes:
      - name: postgresql-vol
        emptyDir: {}
