# Create Contoso Supermarket Queue Monitoring Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-queue-monitoring-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-backend
spec:
  selector:
    app: {{ .Release.Name }}-queue-monitoring-backend
  ports:
  - name: http
    port: 4000
    targetPort: 4000
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-queue-monitoring-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-queue-monitoring-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-queue-monitoring-backend
    spec:
      containers:
        - name: queue-monitoring-backend
          image: {{ .Values.acr_name }}.azurecr.io/{{ .Values.branch_name}}/contoso-supermarket/queue-monitoring-backend:v1.0
          env:
            - name: SQL_HOST
              value: {{ .Release.Name }}-contosodb
            - name: SQL_USERNAME
              value: {{ .Values.postgres.username }}
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespw
                  key: POSTGRES_PASSWORD
            - name: SQL_DATABASE
              value: {{ .Values.postgres.database }}
            - name: ASPNETCORE_URLS
              value : "http://*:4000/"
          ports:
            - containerPort: 4000
      imagePullSecrets:
            - name: acr-secret
---
# Create Contoso Supermarket Queue Monitoring Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-queue-monitoring-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-frontend
spec:
  selector:
    app: {{ .Release.Name }}-queue-monitoring-frontend
  ports:
  - name: http
    port: 81
    targetPort: 8080
  type: LoadBalancer
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-queue-monitoring-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-queue-monitoring-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-queue-monitoring-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-queue-monitoring-frontend
    spec:
      containers:
        - name: queue-monitoring-frontend
          image: {{ .Values.acr_name }}.azurecr.io/{{ .Values.branch_name}}/contoso-supermarket/queue-monitoring-frontend:v1.0
          env:
            - name: BACKEND_API_URL
              value: "http://{{ .Release.Name }}-queue-monitoring-backend:4000"
            - name: BACKEND_API_HOST
              value: "{{ .Release.Name }}-queue-monitoring-backend"
            - name: AI_API_URL
              value: "http://{{ .Release.Name }}-contosoai:8000"
            - name: AI_API_HOST
              value: "{{ .Release.Name }}-contosoai"
            - name: REACT_APP_LIVE_VIEW_ENABLED
              value: "{{ .Values.queue_monitoring_frontend.live_view_enabled }}"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret