apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pos
  namespace: contososupermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: pos
  chart:
    spec:
      chart: ./contoso_supermarket/chart/
