apiVersion: v2
name: contoso_supermarket_pos
description: A helm chart to deploy the Contoso Supermarket Point of Sale application
home: https://github.com/microsoft/jumpstart-agora-apps
type: application
version: 0.1.0
sources:
  - https://github.com/microsoft/jumpstart-agora-apps/tree/main/contoso_supermarket/operations/pos
