postgres:
  username: "postgres"
  password: "admin123"

cosmos:
  endpoint: ""
  database: ""
  container: ""

point-of-sale:
  title: "Contoso Supermarket"
  cameras-enabled: "False"
  cameras-url: ""
  new-category: "True"
  store-id: 1
