apiVersion: v2
name: contoso_supermarket
description: A helm chart to deploy the Contoso Supermarket application
home: https://github.com/github_account/jumpstart-agora-apps
type: application
version: 0.1.0
sources:
  - https://github.com/github_account/jumpstart-agora-apps/tree/branch/contoso_supermarket/operations/contoso_supermarket
