queue_monitoring:
  timezone: "Pacific Standard Time"

postgres:
  username: "postgres"
  database: "contoso"

point_of_sale:
  title: "Contoso Supermarket"
  cameras_enabled: "False"
  cameras_url: ""
  new_category: "True"
  store_id: 1
  store_location: "Seattle"
  holiday_banner: "False"
