# Postgre SQL Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-contosodb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-contosodb
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
# Create PostgreSQL Database Container with local storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-contosodb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-contosodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-contosodb
    spec:
      containers:
      - name: contosodb
        image: postgres:15.0
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrespw
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: contoso
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: {{ .Release.Name }}-postgresql-vol
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ .Release.Name }}-postgresql-vol
          hostPath:
            path: /var/postgresql-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql-file
data:
  initDB.sql: |-
{{ .Files.Get "files/initdb.sql" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      containers:
      - name: initdb
        image: postgres:15.0
        env:
        - name: PGHOST
          value: {{ .Release.Name }}-contosodb
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrespw
              key: POSTGRES_PASSWORD
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgrespw
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        command:
          - sh
          - -c
          - psql -h $PGHOST -U $POSTGRES_USER -d $POSTGRES_DB -f /var/initdb.sql
        volumeMounts:
          - name: init-db-sql
            mountPath: /var/initdb.sql
            subPath: initDB.sql
      restartPolicy: "Never"
      volumes:
        - name: init-db-sql
          configMap:
            name: init-db-sql-file
            items:
            - key: initDB.sql
              path: initDB.sql