name: Build contososupermarket app

on:
  push:
        branches:
            - main
            - Staging
            - Canary
            - Prod
  pull_request:
        types:
            - closed
        branches:
            - main
            - Staging
            - Canary
            - Prod

  workflow_dispatch: {}

permissions:
    contents: write

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: "${{ secrets.ACR_NAME }}.azurecr.io"
          username: ${{ secrets.SPN_CLIENT_ID }}
          password: ${{ secrets.SPN_CLIENT_SECRET }}

      - name: 'Build and push image'
        run: |
          docker build ./contoso_supermarket/developer/pos/src -t "${{ secrets.ACR_NAME }}.azurecr.io/${{github.ref_name}}/contoso-supermarket/pos:latest"
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{github.ref_name}}/contoso-supermarket/pos:latest

      - name: Replace ACR with the correct name
        continue-on-error: true
        env:
            ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
            defaultLine="image: __jumpstartagora__.azurecr.io/contoso-supermarket/pos:latest"
            file="contosopos.yaml"
            acrLine=$(find . -type f -name "contosopos.yaml" -print0 | grep "azurecr.io" "$file" | sed 's/^ *//')
            newLine=$(echo $acrLine | sed -i "s#$acrLine#$defaultLine#g" $file)
            find . -type f -name "contosopos.yaml" -print0 | xargs -0 sed -i "s/__jumpstartagora__/$ACR_NAME/g"

      - name: Replace GitHub account with the correct name
        continue-on-error: true
        run: |
            find . -type f -name "Chart.yaml" -print0 | xargs -0 sed -i "s/__github_account__/$GITHUB_REPOSITORY_OWNER/g"

      - name: Replace GitHub branch with the correct name
        continue-on-error: true
        env:
            GITHUB_BRANCH: ${{github.ref_name}}
        run: |
            find . -type f -name "Chart.yaml" -print0 | xargs -0 sed -i "s/__branch__/$GITHUB_BRANCH/g"

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        continue-on-error: true
        with:
            github_token: ${{ secrets.PAT_GITHUB }}
            commit_message: Push changes
