name: Build contososupermarket image

on:
  push:
        branches:
            - main
            - Staging
            - Canary
            - Prod
  pull_request:
        types:
            - closed
        branches:
            - main
            - Staging
            - Canary
            - Prod

  workflow_dispatch: {}

permissions:
    contents: write

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: "${{ secrets.ACR_NAME }}.azurecr.io"
          username: ${{ secrets.SPN_CLIENT_ID }}
          password: ${{ secrets.SPN_CLIENT_SECRET }}

      - name: 'Build and push image'
        working-directory: contoso_supermarket/developer/pos/
        run: |
          docker build -t "${{ secrets.ACR_NAME }}.azurecr.io/dev/contososupermarket:latest"
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/dev/contososupermarket:latest