name: Build contososupermarket image

on:
  push:
        branches:
            - main
            - Staging
            - Canary
            - Prod
  pull_request:
        types:
            - closed
        branches:
            - main
            - Staging
            - Canary
            - Prod

  workflow_dispatch: {}

permissions:
    contents: write

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      env:
        Version: "0.0.1"
      steps:
      # checkout the repo
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: "${{ secrets.ACR_NAME }}.azurecr.io"
          username: ${{ secrets.SPN_CLIENT_ID }}
          password: ${{ secrets.SPN_CLIENT_SECRET }}

      - name: Get current version
        id: get_version
        run: echo "::set-output name=VERSION::1.2.3"

      - name: Increment version
        run: echo "::set-output name=VERSION::$(echo ${{ steps.get_version.outputs.VERSION }} | awk -F. '{$NF = $NF + 1;} 1' OFS=. )"

      - name: 'Build and push image'
        run: |
          docker build ./contoso_supermarket/developer/pos/src -t "${{ secrets.ACR_NAME }}.azurecr.io/staging/contososupermarket:$Version"
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/staging/contososupermarket:$Version