name: Build contososupermarket app

on:
  push:
        branches:
            - main
            - Staging
            - Canary
            - Prod
  pull_request:
        types:
            - closed
        branches:
            - main
            - Staging
            - Canary
            - Prod

  workflow_dispatch: {}

permissions:
    contents: write

jobs:
  build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: "${{ secrets.ACR_NAME }}.azurecr.io"
          username: ${{ secrets.SPN_CLIENT_ID }}
          password: ${{ secrets.SPN_CLIENT_SECRET }}

      - name: 'Build and push image'
        run: |
          docker build ./contoso_supermarket/developer/pos/src -t "${{ secrets.ACR_NAME }}.azurecr.io/${{github.ref_name}}/contoso-supermarket/pos:latest"
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{github.ref_name}}/contoso-supermarket/pos:latest

      - name: Replace ACR with the correct name
        continue-on-error: true
        env:
            ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
            find . -type f -name "contosopos.yaml" -print0 | xargs -0 sed -i "s/__jumpstartagora__/$ACR_NAME/g"

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        continue-on-error: true
        with:
            github_token: ${{ secrets.PAT_GITHUB }}
            commit_message: Replaced ACR with the correct name

      - name: Set up Helm
        uses: azure/setup-helm@v1
      
      - name: Create Helm chart from Kubernetes manifest
        run: |
              helm create pos-chart
              cp contoso_supermarket/operations/contoso_supermarket/templates/contosopos.yaml pos-chart/templates/
              echo "apiVersion: v2\nname: pos-chart\ndescription: A Helm chart for pos app\nversion: 0.1.0" > pos-chart/Chart.yaml
              helm package pos-chart
      
      - name: Upload Helm chart as artifact
        uses: actions/upload-artifact@v2
        with:
            name: pos-chart
            path: pos-chart-0.1.0.tgz